apiVersion: apps/v1
kind: Deployment
metadata:
  name: conkolla-deployment
spec:
  selector:
    matchLabels:
      app: conkolla
  replicas: 1 # tells deployment to run 1 pod
  template:
    metadata:
      labels:
        app: conkolla
    spec:
      containers:
      - name: conkolla
        image: mar8x/conkolla:latest
        ports:
        - containerPort: 4433
